[Service]
Host = "cloud-ui-go"
Port = 5000
Labels = []
OpenMsg = "cloud ui started"
StaticResourcesPath = "./static"
TimePubSub = 30

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 48080
    PathPrefix = "/core-data"

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'edgex-core-metadata'
    Port = 48081
    PathPrefix = "/core-metadata"

    [Clients.Command]
    Protocol = 'http'
    Host = 'edgex-core-command'
    Port = 48082
    PathPrefix = "/core-command"

    [Clients.Notification]
    Protocol = 'http'
    Host = 'edgex-support-notifications'
    Port = 48060
    PathPrefix = "/support-notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = 'edgex-support-scheduler'
    Port = 48085
    PathPrefix = "/support-scheduler"

    [Clients.RuleEngine]
    Protocol = 'http'
    Host = 'edgex-kuiper'
    Port = 48075
    PathPrefix = "/rule-engine"

    [Clients.Logging]
    Protocol = 'http'
    Host = 'edgex-support-logging'
    Port = 48061
    PathPrefix = "/support-logging"

[Binding]
Type="messagebus"
SubscribeTopic="20151214/Response"
PublishTopic="20151214/Request"

[MessageBus]
Type = "mqtt"
    [MessageBus.SubscribeHost]        
        Host = "172.17.0.1"
        # Host = "broker.emqx.io"        
        Port = 1883
        Protocol = "tcp"
    [MessageBus.PublishHost]
        Host = "172.17.0.1"
        # Host = "broker.emqx.io"
        Port = 	1883
        Protocol = "tcp"
    [MessageBus.Optional]
        # MQTT Specific options
        # Client Identifiers
        Username ="ttdqymlc"
        Password ="x8cN-GqZBJPK"
        ClientId =""
        # Connection information
        Qos          =  "2" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
        KeepAlive    =  "10" # Seconds (must be 2 or greater)
        Retained     = "false"
        AutoReconnect  = "true"
        ConnectTimeout = "10" # Seconds
        # TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
        SkipCertVerify = "true"
        CertFile       = "./certs/client.crt"
        KeyFile        = "./certs/client.key"
        KeyPEMBlock    = ""
        CertPEMBlock   = ""