[Service]
Host = "localhost"
Port = 5000
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"
TimePubSub = 30

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48080
    PathPrefix = "/core-data"

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48081
    PathPrefix = "/core-metadata"

    [Clients.Command]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48082
    PathPrefix = "/core-command"

    [Clients.Notifications]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48060
    PathPrefix = "/support-notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48085
    PathPrefix = "/support-scheduler"

    [Clients.RulesEngine]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48075
    PathPrefix = "/rules-engine"

    [Clients.Logging]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48061
    PathPrefix = "/support-logging"

[Binding]
# Type="http"
Type="messagebus"
SubscribeTopic="20151214/Response"
PublishTopic="20151214/Request"

[MessageBus]
Type = "mqtt"
    [MessageBus.SubscribeHost]                
        # Host = "192.168.43.1"
        Host = "broker.emqx.io"
        Port = 1883
        Protocol = "tcp"
    [MessageBus.PublishHost]        
        Host = "192.168.1.15"
        # Host = "broker.emqx.io"        
        Port = 	1883
        Protocol = "tcp"
    [MessageBus.Optional]
        # Connection information
        Qos          =  "2" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
        KeepAlive    =  "10" # Seconds (must be 2 or greater)
        Retained     = "false"
        AutoReconnect  = "true"
        ConnectTimeout = "10" # Seconds
        # TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
        SkipCertVerify = "true"