[Service]
Host = "edgex-ui-go"
Port = 4000
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

[DynamicProxy]
CoreDataPath     = "/core-data"
CoreDataPort     = "CoreData"
CoreMetadataPath = "/core-metadata"
CoreMetadataPort = "Metadata"
CoreCommandPath  = "/core-command"
CoreCommandPort  = "Command"
CoreExportPath   = "/core-export"
CoreExportPort   = "48071"
RuleEnginePath   = "/rule-engine"
RuleEnginePort   = "48075"
SupportLoggingPath   = "/support-logging"
SupportLoggingPort   = "Logging"
SupportNotificationPath   = "/support-notification"
SupportNotificationPort   = "Notifications"
SupportSchedulerPath   = "/support-scheduler"
SupportSchedulerPort   = "Scheduler"


[Binding]
Type="messagebus"
SubscribeTopic="Response"
PublishTopic="Request"

[MessageBus]
Type = "mqtt"
    [MessageBus.SubscribeHost]
        Host = "m16.cloudmqtt.com"
        Port = 	1888
        Protocol = "tcp"
    [MessageBus.PublishHost]
        Host = "m16.cloudmqtt.com"
        Port = 	14023
        Protocol = "tcp"
    [MessageBus.Optional]
        # MQTT Specific options
        # Client Identifiers
        Username ="ttdqymlc"
        Password ="x8cN-GqZBJPK"
        ClientId =""
        # Connection information
        Qos          =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
        KeepAlive    =  "10" # Seconds (must be 2 or greater)
        Retained     = "false"
        AutoReconnect  = "true"
        ConnectTimeout = "10" # Seconds
        # TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
        SkipCertVerify = "true"
        CertFile       = "./certs/client.crt"
        KeyFile        = "./certs/client.key"
        KeyPEMBlock    = ""
        CertPEMBlock   = ""
